version: '3.8'

services:
  printshop:
    container_name: printshop_app
    build:
      context: .
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - .env
    environment:
      # Явно пробрасываем URI, чтобы Docker соединил приложение с контейнером mongo
      - MONGODB_URI=${MONGODB_URI}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: printshop_mongo
    restart: always
    # Если в .env есть доступы для БД, пропишите их и тут:
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - "27017:27017"
    volumes:
      - printshop_mongo_data:/data/db

volumes:
  printshop_mongo_data:
